name: Test
run-name: "Testing dotchat bus"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
      - name: Run build
        run: npm run build